var data1993 = [
    {
        "cc": "saarg",
        "Country": "Argentina",
        "Year": 1993,
        "Independence": 433,
        "Saving": 146,
        "Unselfishness": 48,
        "Religious": 282,
        "Imagination": 312,
        "Respect": 778,
        "Determination": 291,
        "HardWork": 532,
        "Obedience": 321
    },
    {
        "cc": "sabra",
        "Country": "Brazil",
        "Year": 1993,
        "Independence": 473,
        "Saving": 515,
        "Unselfishness": 504,
        "Religious": 827,
        "Imagination": 220,
        "Respect": 1167,
        "Determination": 460,
        "HardWork": 917,
        "Obedience": 736
    },
    {
        "cc": "aschn",
        "Country": "China",
        "Year": 1993,
        "Independence": 840,
        "Saving": 556,
        "Unselfishness": 309,
        "Religious": 12,
        "Imagination": 267,
        "Respect": 617,
        "Determination": 450,
        "HardWork": 646,
        "Obedience": 85
    },
    {
        "cc": "asind",
        "Country": "India",
        "Year": 1993,
        "Independence": 741,
        "Saving": 556,
        "Unselfishness": 790,
        "Religious": 720,
        "Imagination": 561,
        "Respect": 1479,
        "Determination": 689,
        "HardWork": 1673,
        "Obedience": 1397
    },
    {
        "cc": "asjpn",
        "Country": "Japan",
        "Year": 1993,
        "Independence": 652,
        "Saving": 407,
        "Unselfishness": 445,
        "Religious": 71,
        "Imagination": 243,
        "Respect": 602,
        "Determination": 595,
        "HardWork": 309,
        "Obedience": 102
    },
    {
        "cc": "askor",
        "Country": "South Korea",
        "Year": 1993,
        "Independence": 680,
        "Saving": 666,
        "Unselfishness": 132,
        "Religious": 236,
        "Imagination": 78,
        "Respect": 693,
        "Determination": 389,
        "HardWork": 804,
        "Obedience": 226
    },
    {
        "cc": "namex",
        "Country": "Mexico",
        "Year": 1993,
        "Independence": 724,
        "Saving": 508,
        "Unselfishness": 168,
        "Religious": 617,
        "Imagination": 473,
        "Respect": 985,
        "Determination": 568,
        "HardWork": 356,
        "Obedience": 690
    },
    {
        "cc": "afnga",
        "Country": "Nigeria",
        "Year": 1993,
        "Independence": 164,
        "Saving": 84,
        "Unselfishness": 173,
        "Religious": 739,
        "Imagination": 63,
        "Respect": 751,
        "Determination": 212,
        "HardWork": 816,
        "Obedience": 708
    },
    {
        "cc": "eurus",
        "Country": "Russia",
        "Year": 1993,
        "Independence": 572,
        "Saving": 1194,
        "Unselfishness": 470,
        "Religious": 157,
        "Imagination": 222,
        "Respect": 1376,
        "Determination": 778,
        "HardWork": 1815,
        "Obedience": 507
    },
    {
        "cc": "afzaf",
        "Country": "South Africa",
        "Year": 1993,
        "Independence": 442,
        "Saving": 470,
        "Unselfishness": 544,
        "Religious": 1353,
        "Imagination": 213,
        "Respect": 1676,
        "Determination": 765,
        "HardWork": 817,
        "Obedience": 1145
    },
    {
        "cc": "euesp",
        "Country": "Spain",
        "Year": 1993,
        "Independence": 556,
        "Saving": 251,
        "Unselfishness": 193,
        "Religious": 335,
        "Imagination": 503,
        "Respect": 1061,
        "Determination": 338,
        "HardWork": 769,
        "Obedience": 631
    },
    {
        "cc": "astur",
        "Country": "Turkey",
        "Year": 1993,
        "Independence": 198,
        "Saving": 373,
        "Unselfishness": 286,
        "Religious": 455,
        "Imagination": 240,
        "Respect": 712,
        "Determination": 209,
        "HardWork": 747,
        "Obedience": 323
    }
]