var data2014 = [
    {
        "cc": "saarg",
        "Countries": "Argentina",
        "Year": 2014,
        "Independence": 454,
        "Saving": 138,
        "Unselfishness": 435,
        "Religious": 239,
        "Imagination": 323,
        "Respect": 599,
        "Determination": 259,
        "HardWork": 419,
        "Obedience": 364
    },
    {
        "cc": "ocaus",
        "Countries": "Australia",
        "Year": 2014,
        "Independence": 960,
        "Saving": 454,
        "Unselfishness": 727,
        "Religious": 224,
        "Imagination": 587,
        "Respect": 1275,
        "Determination": 743,
        "HardWork": 873,
        "Obedience": 416
    },
    {
        "cc": "asarm",
        "Countries": "Armenia",
        "Year": 2014,
        "Independence": 308,
        "Saving": 313,
        "Unselfishness": 265,
        "Religious": 419,
        "Imagination": 67,
        "Respect": 620,
        "Determination": 361,
        "HardWork": 901,
        "Obedience": 267
    },
    {
        "cc": "sabra",
        "Countries": "Brazil",
        "Year": 2014,
        "Independence": 558,
        "Saving": 395,
        "Unselfishness": 468,
        "Religious": 740,
        "Imagination": 362,
        "Respect": 954,
        "Determination": 420,
        "HardWork": 953,
        "Obedience": 765
    },
    {
        "cc": "aschn",
        "Countries": "China",
        "Year": 2014,
        "Independence": 1604,
        "Saving": 1165,
        "Unselfishness": 672,
        "Religious": 26,
        "Imagination": 390,
        "Respect": 1200,
        "Determination": 598,
        "HardWork": 1732,
        "Obedience": 172
    },
    {
        "cc": "sacol",
        "Countries": "Colombia",
        "Year": 2014,
        "Independence": 551,
        "Saving": 445,
        "Unselfishness": 692,
        "Religious": 912,
        "Imagination": 314,
        "Respect": 1306,
        "Determination": 368,
        "HardWork": 205,
        "Obedience": 1004
    },
    {
        "cc": "ascyp",
        "Countries": "Cyprus",
        "Year": 2014,
        "Independence": 431,
        "Saving": 306,
        "Unselfishness": 360,
        "Religious": 374,
        "Imagination": 234,
        "Respect": 697,
        "Determination": 410,
        "HardWork": 408,
        "Obedience": 372
    },
    {
        "cc": "euest",
        "Countries": "Estonia",
        "Year": 2014,
        "Independence": 835,
        "Saving": 1181,
        "Unselfishness": 652,
        "Religious": 288,
        "Imagination": 565,
        "Respect": 1295,
        "Determination": 1064,
        "HardWork": 1341,
        "Obedience": 962
    },
    {
        "cc": "eudeu",
        "Countries": "Germany",
        "Year": 2014,
        "Independence": 1503,
        "Saving": 779,
        "Unselfishness": 122,
        "Religious": 247,
        "Imagination": 604,
        "Respect": 1365,
        "Determination": 1220,
        "HardWork": 367,
        "Obedience": 257
    },
    {
        "cc": "afgha",
        "Countries": "Ghana",
        "Year": 2014,
        "Independence": 446,
        "Saving": 378,
        "Unselfishness": 382,
        "Religious": 1096,
        "Imagination": 187,
        "Respect": 1026,
        "Determination": 713,
        "HardWork": 1327,
        "Obedience": 1145
    },
    {
        "cc": "asind",
        "Countries": "India",
        "Year": 2014,
        "Independence": 3665,
        "Saving": 3496,
        "Unselfishness": 3308,
        "Religious": 3388,
        "Imagination": 2821,
        "Respect": 3640,
        "Determination": 3454,
        "HardWork": 3859,
        "Obedience": 3666
    },
    {
        "cc": "asjpn",
        "Countries": "Japan",
        "Year": 2014,
        "Independence": 1654,
        "Saving": 1167,
        "Unselfishness": 1101,
        "Religious": 107,
        "Imagination": 773,
        "Respect": 1578,
        "Determination": 1656,
        "HardWork": 858,
        "Obedience": 121
    },
    {
        "cc": "asjor",
        "Countries": "Jordan",
        "Year": 2014,
        "Independence": 523,
        "Saving": 335,
        "Unselfishness": 438,
        "Religious": 957,
        "Imagination": 177,
        "Respect": 918,
        "Determination": 329,
        "HardWork": 474,
        "Obedience": 674
    },
    {
        "cc": "askor",
        "Countries": "South Korea",
        "Year": 2014,
        "Independence": 694,
        "Saving": 781,
        "Unselfishness": 126,
        "Religious": 299,
        "Imagination": 174,
        "Respect": 490,
        "Determination": 654,
        "HardWork": 772,
        "Obedience": 104
    },
    {
        "cc": "namex",
        "Countries": "Mexico",
        "Year": 2014,
        "Independence": 770,
        "Saving": 691,
        "Unselfishness": 869,
        "Religious": 706,
        "Imagination": 477,
        "Respect": 1558,
        "Determination": 539,
        "HardWork": 761,
        "Obedience": 1091
    },
    {
        "cc": "afmar",
        "Countries": "Morocco",
        "Year": 2014,
        "Independence": 516,
        "Saving": 285,
        "Unselfishness": 304,
        "Religious": 931,
        "Imagination": 287,
        "Respect": 679,
        "Determination": 231,
        "HardWork": 805,
        "Obedience": 351
    },
    {
        "cc": "eunld",
        "Countries": "Netherlands",
        "Year": 2014,
        "Independence": 1154,
        "Saving": 903,
        "Unselfishness": 436,
        "Religious": 265,
        "Imagination": 381,
        "Respect": 1636,
        "Determination": 705,
        "HardWork": 596,
        "Obedience": 487
    },
    {
        "cc": "ocnzl",
        "Countries": "New Zealand",
        "Year": 2014,
        "Independence": 450,
        "Saving": 281,
        "Unselfishness": 308,
        "Religious": 134,
        "Imagination": 305,
        "Respect": 699,
        "Determination": 408,
        "HardWork": 422,
        "Obedience": 203
    },
    {
        "cc": "afnga",
        "Countries": "Nigeria",
        "Year": 2014,
        "Independence": 684,
        "Saving": 335,
        "Unselfishness": 557,
        "Religious": 1279,
        "Imagination": 265,
        "Respect": 1052,
        "Determination": 649,
        "HardWork": 1372,
        "Obedience": 1105
    },
    {
        "cc": "saper",
        "Countries": "Peru",
        "Year": 2014,
        "Independence": 403,
        "Saving": 287,
        "Unselfishness": 467,
        "Religious": 509,
        "Imagination": 202,
        "Respect": 817,
        "Determination": 284,
        "HardWork": 200,
        "Obedience": 633
    },
    {
        "cc": "eupol",
        "Countries": "Poland",
        "Year": 2014,
        "Independence": 419,
        "Saving": 479,
        "Unselfishness": 146,
        "Religious": 382,
        "Imagination": 162,
        "Respect": 798,
        "Determination": 187,
        "HardWork": 173,
        "Obedience": 329
    },
    {
        "cc": "eurus",
        "Countries": "Russia",
        "Year": 2014,
        "Independence": 946,
        "Saving": 1259,
        "Unselfishness": 565,
        "Religious": 347,
        "Imagination": 413,
        "Respect": 1588,
        "Determination": 1136,
        "HardWork": 2112,
        "Obedience": 869
    },
    {
        "cc": "afzaf",
        "Countries": "South Africa",
        "Year": 2014,
        "Independence": 2241,
        "Saving": 1074,
        "Unselfishness": 981,
        "Religious": 1564,
        "Imagination": 991,
        "Respect": 1854,
        "Determination": 1247,
        "HardWork": 2478,
        "Obedience": 1314
    },
    {
        "cc": "afzwe",
        "Countries": "Zimbabwe",
        "Year": 2014,
        "Independence": 586,
        "Saving": 376,
        "Unselfishness": 443,
        "Religious": 894,
        "Imagination": 200,
        "Respect": 957,
        "Determination": 741,
        "HardWork": 1140,
        "Obedience": 1050
    },
    {
        "cc": "euesp",
        "Countries": "Spain",
        "Year": 2014,
        "Independence": 512,
        "Saving": 352,
        "Unselfishness": 417,
        "Religious": 126,
        "Imagination": 295,
        "Respect": 881,
        "Determination": 446,
        "HardWork": 792,
        "Obedience": 373
    },
    {
        "cc": "euswe",
        "Countries": "Sweden",
        "Year": 2014,
        "Independence": 848,
        "Saving": 465,
        "Unselfishness": 366,
        "Religious": 53,
        "Imagination": 564,
        "Respect": 1049,
        "Determination": 405,
        "HardWork": 167,
        "Obedience": 147
    },
    {
        "cc": "astur",
        "Countries": "Turkey",
        "Year": 2014,
        "Independence": 561,
        "Saving": 633,
        "Unselfishness": 445,
        "Religious": 637,
        "Imagination": 453,
        "Respect": 986,
        "Determination": 610,
        "HardWork": 1156,
        "Obedience": 545
    },
    {
        "cc": "euukr",
        "Countries": "Ukraine",
        "Year": 2014,
        "Independence": 643,
        "Saving": 677,
        "Unselfishness": 298,
        "Religious": 334,
        "Imagination": 196,
        "Respect": 886,
        "Determination": 591,
        "HardWork": 1287,
        "Obedience": 635
    },
    {
        "cc": "afegy",
        "Countries": "Egypt",
        "Year": 2014,
        "Independence": 1222,
        "Saving": 343,
        "Unselfishness": 445,
        "Religious": 1270,
        "Imagination": 94,
        "Respect": 949,
        "Determination": 271,
        "HardWork": 768,
        "Obedience": 641
    },
    {
        "cc": "nausa",
        "Countries": "United States",
        "Year": 2014,
        "Independence": 1197,
        "Saving": 705,
        "Unselfishness": 729,
        "Religious": 961,
        "Imagination": 680,
        "Respect": 1603,
        "Determination": 797,
        "HardWork": 1482,
        "Obedience": 624
    }
]

var data2009 = [
    {
        "cc": "saarg",
        "Countries": "Argentina",
        "Year": 2009,
        "Independence": 441,
        "Saving": 155,
        "Unselfishness": 87,
        "Religious": 257,
        "Imagination": 253,
        "Respect": 716,
        "Determination": 236,
        "HardWork": 579,
        "Obedience": 447
    },
    {
        "cc": "ocaus",
        "Countries": "Australia",
        "Year": 2009,
        "Independence": 904,
        "Saving": 499,
        "Unselfishness": 762,
        "Religious": 298,
        "Imagination": 612,
        "Respect": 1303,
        "Determination": 701,
        "HardWork": 690,
        "Obedience": 551
    },
    {
        "cc": "sabra",
        "Countries": "Brazil",
        "Year": 2009,
        "Independence": 428,
        "Saving": 430,
        "Unselfishness": 602,
        "Religious": 836,
        "Imagination": 400,
        "Respect": 967,
        "Determination": 472,
        "HardWork": 917,
        "Obedience": 848
    },
    {
        "cc": "aschn",
        "Countries": "China",
        "Year": 2009,
        "Independence": 1389,
        "Saving": 1227,
        "Unselfishness": 614,
        "Religious": 49,
        "Imagination": 504,
        "Respect": 1288,
        "Determination": 477,
        "HardWork": 1661,
        "Obedience": 274
    },
    {
        "cc": "sacol",
        "Countries": "Colombia",
        "Year": 2009,
        "Independence": 1013,
        "Saving": 1459,
        "Unselfishness": 1615,
        "Religious": 1443,
        "Imagination": 538,
        "Respect": 2545,
        "Determination": 609,
        "HardWork": 574,
        "Obedience": 1792
    },
    {
        "cc": "ascyp",
        "Countries": "Cyprus",
        "Year": 2009,
        "Independence": 875,
        "Saving": 682,
        "Unselfishness": 847,
        "Religious": 1008,
        "Imagination": 270,
        "Respect": 1388,
        "Determination": 847,
        "HardWork": 815,
        "Obedience": 898
    },
    {
        "cc": "euest",
        "Countries": "Estonia",
        "Year": 2009,
        "Independence": 399,
        "Saving": 699,
        "Unselfishness": 233,
        "Religious": 95,
        "Imagination": 172,
        "Respect": 1146,
        "Determination": 729,
        "HardWork": 1226,
        "Obedience": 410
    },
    {
        "cc": "eudeu",
        "Countries": "Germany",
        "Year": 2009,
        "Independence": 3039,
        "Saving": 1697,
        "Unselfishness": 254,
        "Religious": 389,
        "Imagination": 1431,
        "Respect": 2967,
        "Determination": 2328,
        "HardWork": 877,
        "Obedience": 564
    },
    {
        "cc": "afgha",
        "Countries": "Ghana",
        "Year": 2009,
        "Independence": 571,
        "Saving": 300,
        "Unselfishness": 507,
        "Religious": 1114,
        "Imagination": 263,
        "Respect": 1084,
        "Determination": 664,
        "HardWork": 1214,
        "Obedience": 1253
    },
    {
        "cc": "asind",
        "Countries": "India",
        "Year": 2009,
        "Independence": 1338,
        "Saving": 1109,
        "Unselfishness": 684,
        "Religious": 826,
        "Imagination": 509,
        "Respect": 1116,
        "Determination": 815,
        "HardWork": 1626,
        "Obedience": 1118
    },
    {
        "cc": "asjpn",
        "Countries": "Japan",
        "Year": 2009,
        "Independence": 877,
        "Saving": 573,
        "Unselfishness": 551,
        "Religious": 61,
        "Imagination": 338,
        "Respect": 817,
        "Determination": 737,
        "HardWork": 355,
        "Obedience": 56
    },
    {
        "cc": "asjor",
        "Countries": "Jordan",
        "Year": 2009,
        "Independence": 513,
        "Saving": 303,
        "Unselfishness": 672,
        "Religious": 1008,
        "Imagination": 214,
        "Respect": 895,
        "Determination": 369,
        "HardWork": 511,
        "Obedience": 778
    },
    {
        "cc": "askor",
        "Countries": "South Korea",
        "Year": 2009,
        "Independence": 812,
        "Saving": 870,
        "Unselfishness": 139,
        "Religious": 258,
        "Imagination": 494,
        "Respect": 682,
        "Determination": 539,
        "HardWork": 869,
        "Obedience": 162
    },
    {
        "cc": "namex",
        "Countries": "Mexico",
        "Year": 2009,
        "Independence": 637,
        "Saving": 614,
        "Unselfishness": 742,
        "Religious": 606,
        "Imagination": 384,
        "Respect": 1218,
        "Determination": 567,
        "HardWork": 379,
        "Obedience": 909
    },
    {
        "cc": "afmar",
        "Countries": "Morocco",
        "Year": 2009,
        "Independence": 658,
        "Saving": 540,
        "Unselfishness": 439,
        "Religious": 818,
        "Imagination": 314,
        "Respect": 703,
        "Determination": 327,
        "HardWork": 612,
        "Obedience": 611
    },
    {
        "cc": "eunld",
        "Countries": "Netherlands",
        "Year": 2009,
        "Independence": 1450,
        "Saving": 893,
        "Unselfishness": 624,
        "Religious": 304,
        "Imagination": 682,
        "Respect": 2214,
        "Determination": 942,
        "HardWork": 620,
        "Obedience": 874
    },
    {
        "cc": "saper",
        "Countries": "New Zealand",
        "Year": 2009,
        "Independence": 508,
        "Saving": 318,
        "Unselfishness": 367,
        "Religious": 139,
        "Imagination": 335,
        "Respect": 787,
        "Determination": 465,
        "HardWork": 392,
        "Obedience": 233
    },
    {
        "cc": "eupol",
        "Countries": "Peru",
        "Year": 2009,
        "Independence": 412,
        "Saving": 169,
        "Unselfishness": 897,
        "Religious": 676,
        "Imagination": 192,
        "Respect": 993,
        "Determination": 262,
        "HardWork": 813,
        "Obedience": 808
    },
    {
        "cc": "eurus",
        "Countries": "Poland",
        "Year": 2009,
        "Independence": 965,
        "Saving": 1129,
        "Unselfishness": 434,
        "Religious": 950,
        "Imagination": 519,
        "Respect": 1875,
        "Determination": 800,
        "HardWork": 1421,
        "Obedience": 915
    },
    {
        "cc": "afzaf",
        "Countries": "Russia",
        "Year": 2009,
        "Independence": 1343,
        "Saving": 1763,
        "Unselfishness": 653,
        "Religious": 434,
        "Imagination": 506,
        "Respect": 2283,
        "Determination": 1636,
        "HardWork": 3001,
        "Obedience": 1189
    },
    {
        "cc": "afzwe",
        "Countries": "South Africa",
        "Year": 2009,
        "Independence": 1758,
        "Saving": 1102,
        "Unselfishness": 915,
        "Religious": 1678,
        "Imagination": 467,
        "Respect": 2329,
        "Determination": 984,
        "HardWork": 2113,
        "Obedience": 1398
    },
    {
        "cc": "euesp",
        "Countries": "Spain",
        "Year": 2009,
        "Independence": 958,
        "Saving": 757,
        "Unselfishness": 427,
        "Religious": 310,
        "Imagination": 570,
        "Respect": 2077,
        "Determination": 721,
        "HardWork": 1060,
        "Obedience": 878
    },
    {
        "cc": "euswe",
        "Countries": "Sweden",
        "Year": 2009,
        "Independence": 1539,
        "Saving": 972,
        "Unselfishness": 730,
        "Religious": 130,
        "Imagination": 1034,
        "Respect": 2008,
        "Determination": 867,
        "HardWork": 226,
        "Obedience": 347
    },
    {
        "cc": "astur",
        "Countries": "Turkey",
        "Year": 2009,
        "Independence": 998,
        "Saving": 1386,
        "Unselfishness": 961,
        "Religious": 1652,
        "Imagination": 811,
        "Respect": 1948,
        "Determination": 1141,
        "HardWork": 2791,
        "Obedience": 1413
    },
    {
        "cc": "euukr",
        "Countries": "Ukraine",
        "Year": 2009,
        "Independence": 616,
        "Saving": 1194,
        "Unselfishness": 409,
        "Religious": 511,
        "Imagination": 454,
        "Respect": 1470,
        "Determination": 976,
        "HardWork": 2084,
        "Obedience": 1103
    },
    {
        "cc": "afegy",
        "Countries": "Egypt",
        "Year": 2009,
        "Independence": 812,
        "Saving": 830,
        "Unselfishness": 1561,
        "Religious": 2739,
        "Imagination": 321,
        "Respect": 2164,
        "Determination": 672,
        "HardWork": 1738,
        "Obedience": 2063
    },
    {
        "cc": "nausa",
        "Countries": "United States",
        "Year": 2009,
        "Independence": 672,
        "Saving": 373,
        "Unselfishness": 470,
        "Religious": 632,
        "Imagination": 396,
        "Respect": 978,
        "Determination": 502,
        "HardWork": 771,
        "Obedience": 353
    }
]

var data2004 = [
    {
        "cc": "saarg",
        "Countries": "Argentina",
        "Year": 2004,
        "Independence": 465,
        "Saving": 191,
        "Unselfishness": 163,
        "Religious": 557,
        "Imagination": 301,
        "Respect": 901,
        "Determination": 284,
        "HardWork": 728,
        "Obedience": 475
    },
    {
        "cc": "aschn",
        "Countries": "China",
        "Year": 2004,
        "Independence": 741,
        "Saving": 572,
        "Unselfishness": 370,
        "Religious": "",
        "Imagination": 353,
        "Respect": 726,
        "Determination": 160,
        "HardWork": 858,
        "Obedience": 148
    },
    {
        "cc": "euest",
        "Countries": "Estonia",
        "Year": 2004,
        "Independence": 218,
        "Saving": 446,
        "Unselfishness": 165,
        "Religious": 60,
        "Imagination": 107,
        "Respect": 712,
        "Determination": 496,
        "HardWork": 821,
        "Obedience": 285
    },
    {
        "cc": "eudeu",
        "Countries": "Germany",
        "Year": 2004,
        "Independence": 1425,
        "Saving": 748,
        "Unselfishness": 145,
        "Religious": 272,
        "Imagination": 597,
        "Respect": 1479,
        "Determination": 945,
        "HardWork": 456,
        "Obedience": 240
    },
    {
        "cc": "asind",
        "Countries": "India",
        "Year": 2004,
        "Independence": 1125,
        "Saving": 1240,
        "Unselfishness": 732,
        "Religious": 933,
        "Imagination": 562,
        "Respect": 1265,
        "Determination": 928,
        "HardWork": 1699,
        "Obedience": 1115
    },
    {
        "cc": "asjpn",
        "Countries": "Japan",
        "Year": 2004,
        "Independence": 1114,
        "Saving": 655,
        "Unselfishness": 725,
        "Religious": 89,
        "Imagination": 470,
        "Respect": 970,
        "Determination": 940,
        "HardWork": 369,
        "Obedience": 59
    },
    {
        "cc": "asjor",
        "Countries": "Jordan",
        "Year": 2004,
        "Independence": 273,
        "Saving": 237,
        "Unselfishness": 387,
        "Religious": 1027,
        "Imagination": 66,
        "Respect": 823,
        "Determination": 207,
        "HardWork": 548,
        "Obedience": 566
    },
    {
        "cc": "askor",
        "Countries": "South Korea",
        "Year": 2004,
        "Independence": 928,
        "Saving": 810,
        "Unselfishness": 176,
        "Religious": 254,
        "Imagination": 401,
        "Respect": 776,
        "Determination": 509,
        "HardWork": 859,
        "Obedience": 158
    },
    {
        "cc": "namex",
        "Countries": "Mexico",
        "Year": 2004,
        "Independence": 650,
        "Saving": 604,
        "Unselfishness": 760,
        "Religious": 815,
        "Imagination": 374,
        "Respect": 1084,
        "Determination": 505,
        "HardWork": 462,
        "Obedience": 914
    },
    {
        "cc": "afmar",
        "Countries": "Morocco",
        "Year": 2004,
        "Independence": 419,
        "Saving": 445,
        "Unselfishness": 111,
        "Religious": 1115,
        "Imagination": 84,
        "Respect": 930,
        "Determination": 200,
        "HardWork": 919,
        "Obedience": 718
    },
    {
        "cc": "eunld",
        "Countries": "Netherlands",
        "Year": 2004,
        "Independence": 533,
        "Saving": 216,
        "Unselfishness": 280,
        "Religious": 95,
        "Imagination": 320,
        "Respect": 913,
        "Determination": 345,
        "HardWork": 145,
        "Obedience": 256
    },
    {
        "cc": "afnga",
        "Countries": "Nigeria",
        "Year": 2004,
        "Independence": 525,
        "Saving": 208,
        "Unselfishness": 471,
        "Religious": 1369,
        "Imagination": 220,
        "Respect": 1195,
        "Determination": 463,
        "HardWork": 1622,
        "Obedience": 1466
    },
    {
        "cc": "saper",
        "Countries": "Peru",
        "Year": 2004,
        "Independence": 579,
        "Saving": 352,
        "Unselfishness": 755,
        "Religious": 834,
        "Imagination": 344,
        "Respect": 1090,
        "Determination": 503,
        "HardWork": 890,
        "Obedience": 916
    },
    {
        "cc": "eupol",
        "Countries": "Poland",
        "Year": 2004,
        "Independence": 242,
        "Saving": 417,
        "Unselfishness": 133,
        "Religious": 466,
        "Imagination": 141,
        "Respect": 872,
        "Determination": 379,
        "HardWork": 934,
        "Obedience": 354
    },
    {
        "cc": "eurus",
        "Countries": "Russia",
        "Year": 2004,
        "Independence": 769,
        "Saving": 1280,
        "Unselfishness": 513,
        "Religious": 215,
        "Imagination": 174,
        "Respect": 1674,
        "Determination": 1009,
        "HardWork": 2257,
        "Obedience": 841
    },
    {
        "cc": "afzaf",
        "Countries": "South Africa",
        "Year": 2004,
        "Independence": 1874,
        "Saving": 1114,
        "Unselfishness": 876,
        "Religious": 1843,
        "Imagination": 600,
        "Respect": 2223,
        "Determination": 1257,
        "HardWork": 2258,
        "Obedience": 1559
    },
    {
        "cc": "afzwe",
        "Countries": "Zimbabwe",
        "Year": 2004,
        "Independence": 263,
        "Saving": 206,
        "Unselfishness": 330,
        "Religious": 743,
        "Imagination": 111,
        "Respect": 784,
        "Determination": 351,
        "HardWork": 855,
        "Obedience": 683
    },
    {
        "cc": "euesp",
        "Countries": "Spain",
        "Year": 2004,
        "Independence": 940,
        "Saving": 772,
        "Unselfishness": 283,
        "Religious": 481,
        "Imagination": 698,
        "Respect": 1916,
        "Determination": 695,
        "HardWork": 1083,
        "Obedience": 1171
    },
    {
        "cc": "euswe",
        "Countries": "Sweden",
        "Year": 2004,
        "Independence": 1395,
        "Saving": 619,
        "Unselfishness": 664,
        "Religious": 99,
        "Imagination": 820,
        "Respect": 1877,
        "Determination": 593,
        "HardWork": 78,
        "Obedience": 258
    },
    {
        "cc": "astur",
        "Countries": "Turkey",
        "Year": 2004,
        "Independence": 686,
        "Saving": 1339,
        "Unselfishness": 1008,
        "Religious": 2156,
        "Imagination": 1024,
        "Respect": 2881,
        "Determination": 958,
        "HardWork": 3409,
        "Obedience": 1917
    },
    {
        "cc": "euukr",
        "Countries": "Ukraine",
        "Year": 2004,
        "Independence": 382,
        "Saving": 604,
        "Unselfishness": 185,
        "Religious": 217,
        "Imagination": 129,
        "Respect": 784,
        "Determination": 554,
        "HardWork": 1062,
        "Obedience": 424
    },
    {
        "cc": "afegy",
        "Countries": "Egypt",
        "Year": 2004,
        "Independence": 2178,
        "Saving": 241,
        "Unselfishness": 649,
        "Religious": 2620,
        "Imagination": 463,
        "Respect": 1939,
        "Determination": 273,
        "HardWork": 1153,
        "Obedience": 1597
    },
    {
        "cc": "nausa",
        "Countries": "United States",
        "Year": 2004,
        "Independence": 733,
        "Saving": 273,
        "Unselfishness": 467,
        "Religious": 625,
        "Imagination": 361,
        "Respect": 954,
        "Determination": 545,
        "HardWork": 730,
        "Obedience": 384
    }
]

var data1998 = [
    {
        "cc": "saarg",
        "Countries": "Argentina",
        "Year": 1998,
        "Independence": 458,
        "Saving": 172,
        "Unselfishness": 177,
        "Religious": 374,
        "Imagination": 278,
        "Respect": 794,
        "Determination": 307,
        "HardWork": 599,
        "Obedience": 341
    },
    {
        "cc": "ocaus",
        "Countries": "Australia",
        "Year": 1998,
        "Independence": 1084,
        "Saving": 387,
        "Unselfishness": 814,
        "Religious": 438,
        "Imagination": 540,
        "Respect": 1653,
        "Determination": 745,
        "HardWork": 735,
        "Obedience": 598
    },
    {
        "cc": "asarm",
        "Countries": "Armenia",
        "Year": 1998,
        "Independence": 640,
        "Saving": 764,
        "Unselfishness": 612,
        "Religious": 247,
        "Imagination": 314,
        "Respect": 969,
        "Determination": 1145,
        "HardWork": 1671,
        "Obedience": 359
    },
    {
        "cc": "aschn",
        "Countries": "China",
        "Year": 1998,
        "Independence": 752,
        "Saving": 933,
        "Unselfishness": 423,
        "Religious": 50,
        "Imagination": 332,
        "Respect": 645,
        "Determination": 544,
        "HardWork": 1090,
        "Obedience": 439
    },
    {
        "cc": "sacol",
        "Countries": "Colombia",
        "Year": 1998,
        "Independence": 1630,
        "Saving": 1513,
        "Unselfishness": 2250,
        "Religious": 2548,
        "Imagination": 1136,
        "Respect": 4117,
        "Determination": 590,
        "HardWork": 1082,
        "Obedience": 2570
    },
    {
        "cc": "euest",
        "Countries": "Estonia",
        "Year": 1998,
        "Independence": 549,
        "Saving": 310,
        "Unselfishness": 172,
        "Religious": 51,
        "Imagination": 88,
        "Respect": 609,
        "Determination": 500,
        "HardWork": 889,
        "Obedience": 276
    },
    {
        "cc": "asind",
        "Countries": "India",
        "Year": 1998,
        "Independence": 763,
        "Saving": 854,
        "Unselfishness": 460,
        "Religious": 735,
        "Imagination": 220,
        "Respect": 1052,
        "Determination": 588,
        "HardWork": 1461,
        "Obedience": 1426
    },
    {
        "cc": "asjpn",
        "Countries": "Japan",
        "Year": 1998,
        "Independence": 637,
        "Saving": 459,
        "Unselfishness": 398,
        "Religious": 61,
        "Imagination": 273,
        "Respect": 614,
        "Determination": 648,
        "HardWork": 257,
        "Obedience": 66
    },
    {
        "cc": "askor",
        "Countries": "South Korea",
        "Year": 1998,
        "Independence": 746,
        "Saving": 828,
        "Unselfishness": 133,
        "Religious": 207,
        "Imagination": 98,
        "Respect": 585,
        "Determination": 445,
        "HardWork": 777,
        "Obedience": 180
    },
    {
        "cc": "namex",
        "Countries": "Mexico",
        "Year": 1998,
        "Independence": 601,
        "Saving": 697,
        "Unselfishness": 578,
        "Religious": 658,
        "Imagination": 418,
        "Respect": 865,
        "Determination": 600,
        "HardWork": 500,
        "Obedience": 753
    },
    {
        "cc": "ocnzl",
        "Countries": "New Zealand",
        "Year": 1998,
        "Independence": 645,
        "Saving": 302,
        "Unselfishness": 393,
        "Religious": 189,
        "Imagination": 334,
        "Respect": 936,
        "Determination": 472,
        "HardWork": 446,
        "Obedience": 263
    },
    {
        "cc": "afnga",
        "Countries": "Nigeria",
        "Year": 1998,
        "Independence": 403,
        "Saving": 195,
        "Unselfishness": 293,
        "Religious": 1438,
        "Imagination": 121,
        "Respect": 1267,
        "Determination": 777,
        "HardWork": 1653,
        "Obedience": 1425
    },
    {
        "cc": "saper",
        "Countries": "Peru",
        "Year": 1998,
        "Independence": 252,
        "Saving": 231,
        "Unselfishness": 189,
        "Religious": 625,
        "Imagination": 225,
        "Respect": 763,
        "Determination": 293,
        "HardWork": 759,
        "Obedience": 607
    },
    {
        "cc": "eupol",
        "Countries": "Poland",
        "Year": 1998,
        "Independence": 371,
        "Saving": 655,
        "Unselfishness": 160,
        "Religious": "",
        "Imagination": 127,
        "Respect": 940,
        "Determination": "",
        "HardWork": 184,
        "Obedience": 561
    },
    {
        "cc": "eurus",
        "Countries": "Russia",
        "Year": 1998,
        "Independence": 567,
        "Saving": 1121,
        "Unselfishness": 435,
        "Religious": 192,
        "Imagination": 121,
        "Respect": 1417,
        "Determination": 844,
        "HardWork": 1850,
        "Obedience": 694
    },
    {
        "cc": "afzaf",
        "Countries": "South Africa",
        "Year": 1998,
        "Independence": 917,
        "Saving": 843,
        "Unselfishness": 657,
        "Religious": 1794,
        "Imagination": 311,
        "Respect": 2055,
        "Determination": 873,
        "HardWork": 1717,
        "Obedience": 1464
    },
    {
        "cc": "euesp",
        "Countries": "Spain",
        "Year": 1998,
        "Independence": 300,
        "Saving": 231,
        "Unselfishness": 173,
        "Religious": 263,
        "Imagination": 263,
        "Respect": 915,
        "Determination": 257,
        "HardWork": 779,
        "Obedience": 530
    },
    {
        "cc": "euswe",
        "Countries": "Sweden",
        "Year": 1998,
        "Independence": 612,
        "Saving": 425,
        "Unselfishness": 239,
        "Religious": 48,
        "Imagination": 395,
        "Respect": 912,
        "Determination": 319,
        "HardWork": 67,
        "Obedience": 160
    },
    {
        "cc": "astur",
        "Countries": "Turkey",
        "Year": 1998,
        "Independence": 312,
        "Saving": 620,
        "Unselfishness": 374,
        "Religious": 970,
        "Imagination": 422,
        "Respect": 1118,
        "Determination": 357,
        "HardWork": 1322,
        "Obedience": 681
    },
    {
        "cc": "euukr",
        "Countries": "Ukraine",
        "Year": 1998,
        "Independence": 946,
        "Saving": 1374,
        "Unselfishness": 528,
        "Religious": 574,
        "Imagination": 314,
        "Respect": 1720,
        "Determination": 1184,
        "HardWork": 2341,
        "Obedience": 1075
    },
    {
        "cc": "nausa",
        "Countries": "United States",
        "Year": 1998,
        "Independence": 698,
        "Saving": 412,
        "Unselfishness": 555,
        "Religious": 832,
        "Imagination": 409,
        "Respect": 1157,
        "Determination": 640,
        "HardWork": 809,
        "Obedience": 580
    }
]

var data1993 = [
    {
        "cc": "saarg",
        "Country": "Argentina",
        "Year": 1993,
        "Independence": 433,
        "Saving": 146,
        "Unselfishness": 48,
        "Religious": 282,
        "Imagination": 312,
        "Respect": 778,
        "Determination": 291,
        "HardWork": 532,
        "Obedience": 321
    },
    {
        "cc": "sabra",
        "Country": "Brazil",
        "Year": 1993,
        "Independence": 473,
        "Saving": 515,
        "Unselfishness": 504,
        "Religious": 827,
        "Imagination": 220,
        "Respect": 1167,
        "Determination": 460,
        "HardWork": 917,
        "Obedience": 736
    },
    {
        "cc": "aschn",
        "Country": "China",
        "Year": 1993,
        "Independence": 840,
        "Saving": 556,
        "Unselfishness": 309,
        "Religious": 12,
        "Imagination": 267,
        "Respect": 617,
        "Determination": 450,
        "HardWork": 646,
        "Obedience": 85
    },
    {
        "cc": "asind",
        "Country": "India",
        "Year": 1993,
        "Independence": 741,
        "Saving": 556,
        "Unselfishness": 790,
        "Religious": 720,
        "Imagination": 561,
        "Respect": 1479,
        "Determination": 689,
        "HardWork": 1673,
        "Obedience": 1397
    },
    {
        "cc": "asjpn",
        "Country": "Japan",
        "Year": 1993,
        "Independence": 652,
        "Saving": 407,
        "Unselfishness": 445,
        "Religious": 71,
        "Imagination": 243,
        "Respect": 602,
        "Determination": 595,
        "HardWork": 309,
        "Obedience": 102
    },
    {
        "cc": "askor",
        "Country": "South Korea",
        "Year": 1993,
        "Independence": 680,
        "Saving": 666,
        "Unselfishness": 132,
        "Religious": 236,
        "Imagination": 78,
        "Respect": 693,
        "Determination": 389,
        "HardWork": 804,
        "Obedience": 226
    },
    {
        "cc": "namex",
        "Country": "Mexico",
        "Year": 1993,
        "Independence": 724,
        "Saving": 508,
        "Unselfishness": 168,
        "Religious": 617,
        "Imagination": 473,
        "Respect": 985,
        "Determination": 568,
        "HardWork": 356,
        "Obedience": 690
    },
    {
        "cc": "afnga",
        "Country": "Nigeria",
        "Year": 1993,
        "Independence": 164,
        "Saving": 84,
        "Unselfishness": 173,
        "Religious": 739,
        "Imagination": 63,
        "Respect": 751,
        "Determination": 212,
        "HardWork": 816,
        "Obedience": 708
    },
    {
        "cc": "eurus",
        "Country": "Russia",
        "Year": 1993,
        "Independence": 572,
        "Saving": 1194,
        "Unselfishness": 470,
        "Religious": 157,
        "Imagination": 222,
        "Respect": 1376,
        "Determination": 778,
        "HardWork": 1815,
        "Obedience": 507
    },
    {
        "cc": "afzaf",
        "Country": "South Africa",
        "Year": 1993,
        "Independence": 442,
        "Saving": 470,
        "Unselfishness": 544,
        "Religious": 1353,
        "Imagination": 213,
        "Respect": 1676,
        "Determination": 765,
        "HardWork": 817,
        "Obedience": 1145
    },
    {
        "cc": "euesp",
        "Country": "Spain",
        "Year": 1993,
        "Independence": 556,
        "Saving": 251,
        "Unselfishness": 193,
        "Religious": 335,
        "Imagination": 503,
        "Respect": 1061,
        "Determination": 338,
        "HardWork": 769,
        "Obedience": 631
    },
    {
        "cc": "astur",
        "Country": "Turkey",
        "Year": 1993,
        "Independence": 198,
        "Saving": 373,
        "Unselfishness": 286,
        "Religious": 455,
        "Imagination": 240,
        "Respect": 712,
        "Determination": 209,
        "HardWork": 747,
        "Obedience": 323
    }
]